apiVersion: v1
kind: Service
metadata:
  name: apihub-sso
  namespace: apih-stg
  labels:
    app: apihub-sso
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: http
    targetPort: 80
  selector:
    app: apihub-sso
