apiVersion: v1
kind: Service
metadata:
  name: apihub-sso
  namespace: apih-dev
  labels:
    app: apihub-sso
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: http
  selector:
    app: apihub-sso