# [ Temp Dev ] 
# 1. CentOS          => zcplocal.icp:8500/infra/centos:centos7.6.1810
# 2. Apache 2.4.39   => zcplocal.icp:8500/infra/mwpack/apache:2.4.39
#

#base images httpd2.4
FROM httpd:2.4
# Writer
MAINTAINER <rathon_jhjeon>


# docker Agent Path : /usr/local/apache2/sso/webagent
# docker apache Path : /usr/local/apache2/conf

# WebAgent setting
RUN mkdir /appsw
RUN mkdir /appsw/ssoweb
RUN mkdir /appsw/ssoweb/SSO
COPY webagent /appsw/ssoweb/SSO/webagent

# Shell file
COPY exec-dev/rathon.sh /rathon.sh
#RUN chown root:www-data /rathon.sh
RUN chmod 751 /rathon.sh

# Apache setting
COPY exec-dev/httpd.conf  /usr/local/apache2/conf/httpd.conf
COPY exec-dev/WebAgent.conf  /usr/local/apache2/conf/WebAgent.conf
COPY exec-dev/AgentId.dat /usr/local/apache2/conf/AgentId.dat
RUN chmod 755 /usr/local/apache2/conf/WebAgent.conf

#RUN chown -R root:www-data /usr/local/apache2
#RUN chown -R root:www-data /appsw/ssoweb/SSO/webagent
RUN chown daemon:daemon /appsw/ssoweb/SSO/webagent/log
ENV LD_LIBRARY_PATH /appsw/ssoweb/SSO/webagent/bin:appsw/ssoweb/SSO/webagent/bin/thirdparty:${LD_LIBRARY_PATH}
ENV PATH /appsw/ssoweb/SSO/webagent/bin:$PATH
#RUN /bin/bash -c "source /appsw/ssoweb/SSO/webagent/ca_wa_env.sh"

WORKDIR /
CMD ["sh", "-c", "/rathon.sh"]
#CMD ["/bin/bash"]
